// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_167b1PKfUe4nOsiu9AZ80G-fsq6N3Rs',
    appId: '1:1046095092605:web:9023c29418d105b4a78a14',
    messagingSenderId: '1046095092605',
    projectId: 'chililabombwe-pms',
    authDomain: 'chililabombwe-pms.firebaseapp.com',
    storageBucket: 'chililabombwe-pms.firebasestorage.app',
    measurementId: 'G-REWSDJQ6PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJK48e3YYTzeDfLxMITqCHPt85o9gPeIo',
    appId: '1:1046095092605:android:c3ea0ceceb801ec2a78a14',
    messagingSenderId: '1046095092605',
    projectId: 'chililabombwe-pms',
    storageBucket: 'chililabombwe-pms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq7NhlbeXsFA2QOVE_EIF9bH1WwAyykCc',
    appId: '1:1046095092605:ios:4f6776c9df5bcb8aa78a14',
    messagingSenderId: '1046095092605',
    projectId: 'chililabombwe-pms',
    storageBucket: 'chililabombwe-pms.firebasestorage.app',
    iosBundleId: 'com.pms.propertyManagementSystem',
  );
}
