import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:property_management_system/api/database_service.dart';
import 'package:property_management_system/models/user_model.dart';
import 'package:provider/provider.dart';
import 'package:property_management_system/models/property_model.dart';
import 'package:property_management_system/providers/auth_provider.dart';
import 'dart:io';

class AddPropertyScreen extends StatefulWidget {
  const AddPropertyScreen({super.key});

  @override
  State<AddPropertyScreen> createState() => _AddPropertyScreenState();
}

class _AddPropertyScreenState extends State<AddPropertyScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  List<UserModel> _tenants = [];
  UserModel? _selectedTenant;
  final _addressController = TextEditingController();
  final _monthlyRentController = TextEditingController();
  final _ownerNameController = TextEditingController();

  String _selectedType = 'commercial';
  bool _isOccupied = false;
  bool _isLoading = false;

  final List<XFile> _selectedImages = [];
  final ImagePicker _picker = ImagePicker();

  @override
  void initState() {
    super.initState();
    // Pre-fill owner name if available
    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    _ownerNameController.text = authProvider.user?.name ?? '';
    getUsers();
  }

  void getUsers() async {
    setState(() {
      _isLoading = true;
    });
    _tenants = await DatabaseService().getAllTenants();
    setState(() {
      _isLoading = false;
    });
  }

  Future<void> _pickImage() async {
    try {
      final XFile? image = await _picker.pickImage(source: ImageSource.gallery);
      if (image != null) {
        setState(() {
          _selectedImages.add(image);
        });
      }
    } catch (e) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('Failed to pick image: $e')));
    }
  }

  Future<void> _removeImage(int index) async {
    setState(() {
      _selectedImages.removeAt(index);
    });
  }

  Future<void> _submitForm() async {
    if (_formKey.currentState!.validate()) {
      setState(() => _isLoading = true);

      try {
        final authProvider = Provider.of<AuthProvider>(context, listen: false);
        final databaseService = DatabaseService();

        // Create property model
        final property = PropertyModel(
          id: '',
          // Will be generated by Firestore
          name: _nameController.text.trim(),
          tenantId: _selectedTenant?.uid,
          tenant: _selectedTenant,
          ownerUid: authProvider.user!.uid,
          ownerName: _ownerNameController.text.trim(),
          address: _addressController.text.trim(),
          type: _selectedType,
          monthlyRent: double.parse(_monthlyRentController.text),
          isOccupied: _isOccupied,
          createdAt: DateTime.now(),
          lastUpdated: DateTime.now(),
        );

        // Add property to database
        await databaseService.addProperty(property);

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Property added successfully!')),
          );
          Navigator.pop(context);
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(
            context,
          ).showSnackBar(SnackBar(content: Text('Failed to add property: $e')));
        }
      } finally {
        if (mounted) {
          setState(() => _isLoading = false);
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Add New Property'),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Property Images
              const Text(
                'Property Images',
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.w500),
              ),
              const SizedBox(height: 8),
              // SizedBox(
              //   height: 100,
              //   child: Row(
              //     children: [
              //       // Add Image Button
              //       GestureDetector(
              //         onTap: _pickImage,
              //         child: Container(
              //           width: 80,
              //           height: 80,
              //           decoration: BoxDecoration(
              //             color: Colors.grey[200],
              //             borderRadius: BorderRadius.circular(8),
              //             border: Border.all(color: Colors.grey[300]!),
              //           ),
              //           child: const Icon(Icons.add, size: 30),
              //         ),
              //       ),
              //       const SizedBox(width: 8),
              //       // Selected Images
              //       // Expanded(
              //       //   child: ListView.builder(
              //       //     scrollDirection: Axis.horizontal,
              //       //     itemCount: _selectedImages.length,
              //       //     itemBuilder: (context, index) {
              //       //       return Stack(
              //       //         children: [
              //       //           Container(
              //       //             width: 80,
              //       //             height: 80,
              //       //             margin: const EdgeInsets.only(right: 8),
              //       //             decoration: BoxDecoration(
              //       //               borderRadius: BorderRadius.circular(8),
              //       //               image: DecorationImage(
              //       //                 image: FileImage(
              //       //                   File(_selectedImages[index].path),
              //       //                 ),
              //       //                 fit: BoxFit.cover,
              //       //               ),
              //       //             ),
              //       //           ),
              //       //           Positioned(
              //       //             top: 0,
              //       //             right: 0,
              //       //             child: GestureDetector(
              //       //               onTap: () => _removeImage(index),
              //       //               child: Container(
              //       //                 padding: const EdgeInsets.all(2),
              //       //                 decoration: const BoxDecoration(
              //       //                   color: Colors.red,
              //       //                   shape: BoxShape.circle,
              //       //                 ),
              //       //                 child: const Icon(
              //       //                   Icons.close,
              //       //                   size: 14,
              //       //                   color: Colors.white,
              //       //                 ),
              //       //               ),
              //       //             ),
              //       //           ),
              //       //         ],
              //       //       );
              //       //     },
              //       //   ),
              //       // ),
              //     ],
              //   ),
              // ),
              // const SizedBox(height: 24),

              // Property Name
              TextFormField(
                controller: _nameController,
                decoration: InputDecoration(
                  labelText: 'Property Name',
                  prefixIcon: const Icon(Icons.business),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a property name';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // Address
              TextFormField(
                controller: _addressController,
                decoration: InputDecoration(
                  labelText: 'Address',
                  prefixIcon: const Icon(Icons.location_on),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter the property address';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),
              DropdownButtonFormField<UserModel>(
                validator: (value) {
                  if (value == null) {
                    return 'Please enter the owner name';
                  }
                  return null;
                },
                decoration: InputDecoration(
                  labelText: 'Tenant (Optional)',
                  prefixIcon: const Icon(Icons.person),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
                items: _tenants
                    .map((e) => DropdownMenuItem(value: e, child: Text(e.name)))
                    .toList(),
                onChanged: (e) {
                  _selectedTenant = e;
                },
              ),
              // Owner Name
              const SizedBox(height: 16),

              // Property Type
              DropdownButtonFormField<String>(
                value: _selectedType,
                decoration: InputDecoration(
                  labelText: 'Property Type',
                  prefixIcon: const Icon(Icons.category),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
                items: const [
                  DropdownMenuItem(
                    value: 'commercial',
                    child: Text('Commercial'),
                  ),
                  DropdownMenuItem(
                    value: 'residential',
                    child: Text('Residential'),
                  ),
                  DropdownMenuItem(value: 'mixed', child: Text('Mixed Use')),
                ],
                onChanged: (value) {
                  setState(() {
                    _selectedType = value!;
                  });
                },
              ),
              const SizedBox(height: 16),

              // Monthly Rent
              TextFormField(
                controller: _monthlyRentController,
                keyboardType: TextInputType.number,
                decoration: InputDecoration(
                  labelText: 'Monthly Rent (K)',
                  prefixIcon: const Icon(Icons.attach_money),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter the monthly rent';
                  }
                  if (double.tryParse(value) == null) {
                    return 'Please enter a valid number';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // Occupancy Status
              Row(
                children: [
                  const Text('Occupied', style: TextStyle(fontSize: 16)),
                  const Spacer(),
                  Switch(
                    value: _isOccupied,
                    onChanged: (value) {
                      setState(() {
                        _isOccupied = value;
                      });
                    },
                  ),
                ],
              ),
              const SizedBox(height: 24),

              // Submit Button
              ElevatedButton(
                onPressed: _isLoading ? null : _submitForm,
                style: ElevatedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 16),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
                child: _isLoading
                    ? const SizedBox(
                        height: 20,
                        width: 20,
                        child: CircularProgressIndicator(
                          strokeWidth: 2,
                          valueColor: AlwaysStoppedAnimation<Color>(
                            Colors.white,
                          ),
                        ),
                      )
                    : const Text(
                        'Add Property',
                        style: TextStyle(fontSize: 16),
                      ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    _nameController.dispose();
    _addressController.dispose();
    _monthlyRentController.dispose();
    _ownerNameController.dispose();
    super.dispose();
  }
}
