import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:property_management_system/api/database_service.dart';
import 'package:property_management_system/models/property_model.dart';
import 'package:provider/provider.dart';
import 'package:property_management_system/models/maintenance_model.dart';
import 'package:property_management_system/providers/auth_provider.dart';
import 'dart:io';

class CreateMaintenanceScreen extends StatefulWidget {
  const CreateMaintenanceScreen({super.key});

  @override
  State<CreateMaintenanceScreen> createState() => _CreateMaintenanceScreenState();
}

class _CreateMaintenanceScreenState extends State<CreateMaintenanceScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();

  String _selectedPriority = 'medium';
  String _selectedCategory = 'plumbing';
  bool _isLoading = false;

  final List<XFile> _selectedImages = [];
  final ImagePicker _picker = ImagePicker();

  // List of available properties (would be fetched from database)
  List<PropertyModel> _availableProperties = [];
  PropertyModel? _selectedProperty;

  @override
  void initState() {
    super.initState();
    // In a real app, you would fetch the user's properties here
    _loadUserProperties();
  }

  Future<void> _loadUserProperties() async {
    // Simulate loading properties from database
    // In a real app, you would use DatabaseService to get user's properties
    final authProvider = context.read<AuthProvider>().user;

    final database = DatabaseService();

   final response = await  database.getPropertiesByOwner(authProvider!.uid, role: "tenantId").first;

    setState(() {
     _availableProperties = response;
    });
  }

  Future<void> _pickImage() async {
    try {
      final XFile? image = await _picker.pickImage(source: ImageSource.gallery);
      if (image != null) {
        setState(() {
          _selectedImages.add(image);
        });
      }
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Failed to pick image: $e')),
      );
    }
  }

  Future<void> _removeImage(int index) async {
    setState(() {
      _selectedImages.removeAt(index);
    });
  }

  Future<void> _submitRequest() async {
    if (_formKey.currentState!.validate()) {
      if (_selectedProperty == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Please select a property')),
        );
        return;
      }

      setState(() => _isLoading = true);

      try {
        final authProvider = Provider.of<AuthProvider>(context, listen: false);
        final databaseService = DatabaseService();

        // Create maintenance request model
        final maintenanceRequest = MaintenanceModel(
          id: '', // Will be generated by Firestore
          propertyId: _selectedProperty!.id,
          requesterUid: authProvider.user!.uid,
          requesterName: authProvider.user!.name,
          title: _titleController.text.trim(),
          description: _descriptionController.text.trim(),
          category: _selectedCategory,
          priority: _selectedPriority,
          status: 'pending',
          images: [], // Would be uploaded to storage and URLs stored here
          createdAt: DateTime.now(), propertyNumber: _selectedProperty!.type, propertyOwnerId: _selectedProperty!.ownerUid
        );

        // Add maintenance request to database
        await databaseService.addMaintenanceRequest(maintenanceRequest);

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Maintenance request submitted successfully!')),
          );
          Navigator.pop(context);
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Failed to submit request: $e')),
          );
        }
      } finally {
        if (mounted) {
          setState(() => _isLoading = false);
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Maintenance Request'),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Property Selection
              const Text(
                'Select Property',
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.w500),
              ),
              const SizedBox(height: 8),
              DropdownButtonFormField<PropertyModel>(
                value: _selectedProperty,
                decoration: InputDecoration(
                  labelText: 'Property',
                  prefixIcon: const Icon(Icons.business),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
                items: _availableProperties.map((property) {
                  return DropdownMenuItem(
                    value: property,
                    child: Text(property.name),
                  );
                }).toList(),
                onChanged: (value) {
                  setState(() {
                    _selectedProperty = value;
                  });
                },
                validator: (value) {
                  if (value == null) {
                    return 'Please select a property';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 24),

              // Request Title
              TextFormField(
                controller: _titleController,
                decoration: InputDecoration(
                  labelText: 'Issue Title',
                  hintText: 'e.g., Leaking faucet in kitchen',
                  prefixIcon: const Icon(Icons.title),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a title for the issue';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // Category Selection
              const Text(
                'Category',
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.w500),
              ),
              const SizedBox(height: 8),
              DropdownButtonFormField<String>(
                value: _selectedCategory,
                decoration: InputDecoration(
                  prefixIcon: const Icon(Icons.category),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
                items: const [
                  DropdownMenuItem(
                    value: 'plumbing',
                    child: Text('Plumbing'),
                  ),
                  DropdownMenuItem(
                    value: 'electrical',
                    child: Text('Electrical'),
                  ),
                  DropdownMenuItem(
                    value: 'structural',
                    child: Text('Structural'),
                  ),
                  DropdownMenuItem(
                    value: 'appliance',
                    child: Text('Appliance'),
                  ),
                  DropdownMenuItem(
                    value: 'heating',
                    child: Text('Heating/Cooling'),
                  ),
                  DropdownMenuItem(
                    value: 'other',
                    child: Text('Other'),
                  ),
                ],
                onChanged: (value) {
                  setState(() {
                    _selectedCategory = value!;
                  });
                },
              ),
              const SizedBox(height: 16),

              // Priority Selection
              const Text(
                'Priority',
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.w500),
              ),
              const SizedBox(height: 8),
              DropdownButtonFormField<String>(
                isExpanded: true,
                value: _selectedPriority,
                decoration: InputDecoration(
                  prefixIcon: const Icon(Icons.priority_high),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
                items: const [
                  DropdownMenuItem(
                    value: 'low',
                    child: Row(
                      children: [
                        Icon(Icons.arrow_downward, color: Colors.blue, size: 16),
                        SizedBox(width: 8),
                        Text('Low Priority'),
                      ],
                    ),
                  ),
                  DropdownMenuItem(
                    value: 'medium',
                    child: Row(
                      children: [
                        Icon(Icons.remove, color: Colors.orange, size: 16),
                        SizedBox(width: 8),
                        Text('Medium Priority'),
                      ],
                    ),
                  ),
                  DropdownMenuItem(
                    value: 'high',
                    child: Row(
                      children: [
                        Icon(Icons.arrow_upward, color: Colors.red, size: 16),
                        SizedBox(width: 8),
                        Text('High Priority'),
                      ],
                    ),
                  ),
                  DropdownMenuItem(
                    value: 'urgent',
                    child: Row(
                      children: [
                        Icon(Icons.warning, color: Colors.deepOrange, size: 16),
                        SizedBox(width: 8),
                        Expanded(child: Text('Urgent - Immediate attention needed')),
                      ],
                    ),
                  ),
                ],
                onChanged: (value) {
                  setState(() {
                    _selectedPriority = value!;
                  });
                },
              ),
              const SizedBox(height: 16),

              // Description
              TextFormField(
                controller: _descriptionController,
                maxLines: 4,
                decoration: InputDecoration(
                  labelText: 'Description',
                  hintText: 'Describe the issue in detail...',
                  alignLabelWithHint: true,
                  prefixIcon: const Icon(Icons.description),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please describe the issue';
                  }
                  if (value.length < 10) {
                    return 'Please provide more details (at least 10 characters)';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 24),

              // Attach Images
              const Text(
                'Attach Photos (Optional)',
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.w500),
              ),
              const SizedBox(height: 8),
              SizedBox(
                height: 100,
                child: Row(
                  children: [
                    // Add Image Button
                    GestureDetector(
                      onTap: _pickImage,
                      child: Container(
                        width: 80,
                        height: 80,
                        decoration: BoxDecoration(
                          color: Colors.grey[200],
                          borderRadius: BorderRadius.circular(8),
                          border: Border.all(color: Colors.grey[300]!),
                        ),
                        child: const Icon(Icons.add_a_photo, size: 30),
                      ),
                    ),
                    const SizedBox(width: 8),
                    // Selected Images
                    Expanded(
                      child: ListView.builder(
                        scrollDirection: Axis.horizontal,
                        itemCount: _selectedImages.length,
                        itemBuilder: (context, index) {
                          return Stack(
                            children: [
                              Container(
                                width: 80,
                                height: 80,
                                margin: const EdgeInsets.only(right: 8),
                                decoration: BoxDecoration(
                                  borderRadius: BorderRadius.circular(8),
                                  image: DecorationImage(
                                    image: FileImage(File(_selectedImages[index].path)),
                                    fit: BoxFit.cover,
                                  ),
                                ),
                              ),
                              Positioned(
                                top: 0,
                                right: 0,
                                child: GestureDetector(
                                  onTap: () => _removeImage(index),
                                  child: Container(
                                    padding: const EdgeInsets.all(2),
                                    decoration: const BoxDecoration(
                                      color: Colors.red,
                                      shape: BoxShape.circle,
                                    ),
                                    child: const Icon(
                                      Icons.close,
                                      size: 14,
                                      color: Colors.white,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          );
                        },
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 32),

              // Submit Button
              ElevatedButton(
                onPressed: _isLoading ? null : _submitRequest,
                style: ElevatedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 16),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
                child: _isLoading
                    ? const SizedBox(
                  height: 20,
                  width: 20,
                  child: CircularProgressIndicator(
                    strokeWidth: 2,
                    valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                  ),
                )
                    : const Text(
                  'Submit Request',
                  style: TextStyle(fontSize: 16),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }
}