import 'package:flutter/material.dart';
import 'package:property_management_system/api/database_service.dart';
import 'package:property_management_system/models/activity_model.dart';
import 'package:provider/provider.dart';
import 'package:property_management_system/models/property_model.dart';
import 'package:property_management_system/models/payment_model.dart';
import 'package:property_management_system/models/maintenance_model.dart';
import 'package:property_management_system/providers/auth_provider.dart';
import 'package:intl/intl.dart';

class DashboardScreen extends StatefulWidget {
  const DashboardScreen({super.key});

  @override
  State<DashboardScreen> createState() => _DashboardScreenState();
}

class _DashboardScreenState extends State<DashboardScreen> {
  PropertyModel? _tenantProperty;
  List<PaymentModel> _recentPayments = [];
  Map<String, dynamic> _stats = {};
  List<ActivityModel> _recentActivities = [];
  bool _isLoading = true;
  bool _isPaying = false;

  @override
  void initState() {
    super.initState();
    _loadDashboardData();
  }

  Future<void> _loadDashboardData() async {
    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    final databaseService = DatabaseService();
    final user = authProvider.user;

    try {
      if (user?.role == 'tenant') {
        // For tenants, get their assigned property, payments, and maintenance requests
        final properties = await databaseService.getAllPropertiesFuture();
        _tenantProperty = properties.firstWhere(
              (property) => property.isOccupied && property.tenantId == user!.uid,
          orElse: () => PropertyModel(
            id: '',
            name: 'No Property Assigned',
            ownerUid: '',
            ownerName: '',
            address: '',
            type: '',
            monthlyRent: 0,
            isOccupied: false,
            createdAt: DateTime.now(),
            lastUpdated: DateTime.now(),
          ),
        );

        _recentPayments = await databaseService.getPaymentsByUserFuture(user!.uid);

      } else {
       _stats = await databaseService.getDashboardStats(authProvider.user!.uid);
       _recentActivities = await databaseService.getOwnerRecentActivities(user!.uid);

      }
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Failed to load dashboard data: $e')),
      );
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _makePayment() async {
    if (_tenantProperty == null) return;

    setState(() => _isPaying = true);

    try {
      final databaseService = DatabaseService();
      final authProvider = Provider.of<AuthProvider>(context, listen: false);
      final user = authProvider.user;

      // Create a new payment record
      final payment = PaymentModel(
        id: '', // Will be generated by Firestore
        propertyId: _tenantProperty!.id,
        propertyOwnerId: _tenantProperty!.ownerUid,
        propertyName: _tenantProperty!.name,
        payerUid: user!.uid,
        payerName: user.name,
        amount: _tenantProperty!.monthlyRent,
        description: 'Monthly Rent Payment',
        status: 'completed', // Mark as completed for demo
        createdAt: DateTime.now(),
        paidDate: DateTime.now(),
      );

      await databaseService.addPayment(payment);

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Payment successful!')),
      );

      // Refresh the data
      _loadDashboardData();
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Payment failed: $e')),
      );
    } finally {
      setState(() => _isPaying = false);
    }
  }

  Widget _buildTenantDashboard() {
    if (_isLoading) {
      return const Center(child: CircularProgressIndicator());
    }

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Welcome Card
          Container(
            width: double.infinity,
            padding: const EdgeInsets.all(20),
            decoration: BoxDecoration(
              gradient: const LinearGradient(
                colors: [Color(0xFF1565C0), Color(0xFF1976D2)],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
              borderRadius: BorderRadius.circular(12),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [

                const Text(
                  'Welcome, Tenant',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 24,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 8),
                Text(
                  'Chililabombwe Municipal Council',
                  style: TextStyle(
                    color: Colors.white.withOpacity(0.9),
                    fontSize: 16,
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 24),

          // Property Details Card
          if (_tenantProperty != null && _tenantProperty!.id.isNotEmpty)
            Card(
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'Your Property',
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 16),
                    _buildPropertyInfo('Name', _tenantProperty!.name),
                    _buildPropertyInfo('Address', _tenantProperty!.address),
                    _buildPropertyInfo('Type', _tenantProperty!.type),
                    _buildPropertyInfo(
                      'Monthly Rent',
                      'K ${_tenantProperty!.monthlyRent.toStringAsFixed(2)}',
                    ),
                    _buildPropertyInfo(
                      'Status',
                      _tenantProperty!.isOccupied ? 'Occupied' : 'Vacant',
                      statusColor: _tenantProperty!.isOccupied ? Colors.green : Colors.orange,
                    ),
                  ],
                ),
              ),
            )
          else
            const Card(
              child: Padding(
                padding: EdgeInsets.all(16),
                child: Text('No property assigned to you yet.'),
              ),
            ),

          const SizedBox(height: 24),

          // Payment Section
          if (_tenantProperty != null && _tenantProperty!.id.isNotEmpty)
            Card(
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'Make Payment',
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 16),
                    const Text(
                      'Monthly Rent:',
                      style: TextStyle(fontSize: 16),
                    ),
                    Text(
                      'K ${_tenantProperty!.monthlyRent.toStringAsFixed(2)}',
                      style: const TextStyle(
                        fontSize: 20,
                        fontWeight: FontWeight.bold,
                        color: Color(0xFF1565C0),
                      ),
                    ),
                    const SizedBox(height: 16),
                    const Text(
                      'Due Date: 5th of each month',
                      style: TextStyle(color: Colors.grey),
                    ),
                    const SizedBox(height: 24),
                    ElevatedButton(
                      onPressed: _isPaying ? null : _makePayment,
                      style: ElevatedButton.styleFrom(
                        minimumSize: const Size(double.infinity, 50),
                      ),
                      child: _isPaying
                          ? const SizedBox(
                        height: 20,
                        width: 20,
                        child: CircularProgressIndicator(
                          strokeWidth: 2,
                          valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                        ),
                      )
                          : const Text(
                        'Pay Now',
                        style: TextStyle(fontSize: 16),
                      ),
                    ),
                  ],
                ),
              ),
            ),

          const SizedBox(height: 24),

          // Recent Payments
          Card(
            child: Padding(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text(
                    'Recent Payments',
                    style: TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 16),
                  _recentPayments.isEmpty
                      ? const Text('No recent payments')
                      : Column(
                    children: _recentPayments
                        .take(3)
                        .map((payment) => _buildPaymentItem(payment))
                        .toList(),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildPropertyInfo(String label, String value, {Color? statusColor}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            width: 120,
            child: Text(
              label,
              style: const TextStyle(fontWeight: FontWeight.w500),
            ),
          ),
          const SizedBox(width: 8),
          Expanded(
            child: Text(
              value,
              style: TextStyle(
                color: statusColor,
                fontWeight: statusColor != null ? FontWeight.w500 : null,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildPaymentItem(PaymentModel payment) {
    return ListTile(
      contentPadding: EdgeInsets.zero,
      leading: Container(
        width: 40,
        height: 40,
        decoration: BoxDecoration(
          color: payment.status == 'completed' ? Colors.green[100] : Colors.orange[100],
          borderRadius: BorderRadius.circular(8),
        ),
        child: Icon(
          payment.status == 'completed' ? Icons.check_circle : Icons.pending,
          color: payment.status == 'completed' ? Colors.green : Colors.orange,
          size: 20,
        ),
      ),
      title: Text('K ${payment.amount.toStringAsFixed(2)}'),
      subtitle: Text(DateFormat('MMM dd, yyyy').format(payment.createdAt)),
      trailing: Text(
        payment.status.toUpperCase(),
        style: TextStyle(
          color: payment.status == 'completed' ? Colors.green : Colors.orange,
          fontWeight: FontWeight.w500,
        ),
      ),
    );
  }



  @override
  Widget build(BuildContext context) {
    final authProvider = Provider.of<AuthProvider>(context);
    final isTenant = authProvider.user?.role == 'tenant';

    return Scaffold(
      appBar: AppBar(
        title: const Text('Dashboard'),
        actions: [
          IconButton(
            icon: const Icon(Icons.notifications),
            onPressed: () {
              // Handle notifications
            },
          ),
          IconButton(
            icon: const Icon(Icons.refresh),
            onPressed: _loadDashboardData,
          ),
        ],
      ),
      body: isTenant ? _buildTenantDashboard() : _buildAdminDashboard(),
    );
  }

  // Keep the original admin dashboard as before
  Widget _buildAdminDashboard() {
    // Your original dashboard implementation here
    return _isLoading? Center(child: CircularProgressIndicator(),) : SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Welcome Card
          Container(
            width: double.infinity,
            padding: const EdgeInsets.all(20),
            decoration: BoxDecoration(
              gradient: const LinearGradient(
                colors: [Color(0xFF1565C0), Color(0xFF1976D2)],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
              borderRadius: BorderRadius.circular(12),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text(
                  'Welcome, John Doe',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 24,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 8),
                Text(
                  'Chililabombwe Municipal Council',
                  style: TextStyle(
                    color: Colors.white.withOpacity(0.9),
                    fontSize: 16,
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 24),

          // Stats Grid
          GridView.count(
            shrinkWrap: true,
            physics: const NeverScrollableScrollPhysics(),
            crossAxisCount: 2,
            crossAxisSpacing: 16,
            mainAxisSpacing: 16,
            childAspectRatio: 1.5,
            children: [
              _buildStatCard(
                title: 'Total Properties',
                value: '${_stats['totalProperties'] ?? 0}',
                icon: Icons.business,
                color: Colors.blue,
              ),
              _buildStatCard(
                title: 'Pending Payments',
                value: '${_stats['pendingPayments'] ?? 0}',
                icon: Icons.payment,
                color: Colors.orange,
              ),
                _buildStatCard(
                  title: 'This Month Revenue',
                  value: 'K ${_stats['monthlyRevenue'] ?? 0}',
                  icon: Icons.trending_up,
                  color: Colors.green,
                ),
              _buildStatCard(
                title: 'Maintenance Requests',
                value: '${_stats['activeMaintenanceRequests'] ?? 0}',
                icon: Icons.build,
                color: Colors.purple,
              ),
            ],
          ),

          const SizedBox(height: 24),

          // Recent Activities
          const Text(
            'Recent Activities',
            style: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 16),
          Card(
            child: _recentActivities.isEmpty
                ? const Padding(
              padding: EdgeInsets.all(16),
              child: Text('No recent activities found.'),
            )
                : ListView.builder(
              shrinkWrap: true,
              physics: const NeverScrollableScrollPhysics(),
              itemCount: _recentActivities.length,
              itemBuilder: (context, index) {
                final activity = _recentActivities[index];
                return _buildActivityItem(
                  icon: activity.icon,
                  title: activity.title,
                  subtitle: activity.subtitle,
                  time: DateFormat('MMM dd, yyyy – HH:mm').format(activity.createdAt),
                  color: activity.color,
                );
              },
            ),
          )
        ],
      ),
    );
  }

  Widget _buildStatCard({
    required String title,
    required String value,
    required IconData icon,
    required Color color,
  }) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Icon(icon, color: color, size: 24),
                Container(
                  padding: const EdgeInsets.all(4),
                  decoration: BoxDecoration(
                    color: color.withOpacity(0.1),
                    borderRadius: BorderRadius.circular(4),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 8),
            Text(
              value,
              style: const TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
              ),
            ),
            Text(
              title,
              style: TextStyle(
                fontSize: 12,
                color: Colors.grey[600],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildActivityItem({
    required IconData icon,
    required String title,
    required String subtitle,
    required String time,
    required Color color,
  }) {
    return ListTile(
      leading: Container(
        padding: const EdgeInsets.all(8),
        decoration: BoxDecoration(
          color: color.withOpacity(0.1),
          borderRadius: BorderRadius.circular(8),
        ),
        child: Icon(icon, color: color, size: 20),
      ),
      title: Text(title, style: const TextStyle(fontWeight: FontWeight.w500)),
      subtitle: Text(subtitle),
      trailing: Text(
        time,
        style: TextStyle(
          fontSize: 12,
          color: Colors.grey[600],
        ),
      ),
    );
  }
}